# Generated by Django 4.1 on 2022-08-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 접속일')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField()),
                ('email', models.CharField(max_length=30)),
                ('sex', models.BooleanField()),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
