# Generated by Django 4.1 on 2022-08-31 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBoard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 접속일')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('contents', models.CharField(max_length=300, verbose_name='내용')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('baseboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.baseboard')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.user', verbose_name='user_id')),
            ],
            options={
                'db_table': 'operation',
            },
            bases=('board.baseboard',),
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('baseboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.baseboard')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.user', verbose_name='user_id')),
            ],
            options={
                'db_table': 'notice',
            },
            bases=('board.baseboard',),
        ),
        migrations.CreateModel(
            name='FreeBoard',
            fields=[
                ('baseboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.baseboard')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.user', verbose_name='user_id')),
            ],
            options={
                'db_table': 'free',
            },
            bases=('board.baseboard',),
        ),
    ]
